### ISSUE TITLE
sublime.active_window().views() error - ST v.2 only

### ISSUE THREAD

**Issue by mattst** [aziz/SublimeFileBrowser#62]
Using: SublimeFileBrowser v.0.5.3 on ST v. 2.0.2 Build 2221.

SublimeFileBrowser is not working in ST v. 2, although it was recently. There is an error reported by console when it loads the plugin.

Console says:

    Reloading plugin snip/.config/sublime-text-2/Packages/FileBrowser/dired.py
    Traceback (most recent call last):
      File "./sublime_plugin.py", line 62, in reload_plugin
      File "./dired.py", line 82, in <module>
        plugin_loaded()
      File "./dired.py", line 77, in plugin_loaded
        for v in sublime.active_window().views():
    AttributeError: 'NoneType' object has no attribute 'views'

The same version of SublimeFileBrowser is working fine with ST v. 3 Build 3065.

Hope this helps.

**Comment by vovkkk** [comment]
I’m going disable that feature for ST2 since it prevents ability to even start SFB.

**Comment by vovkkk** [comment]
However, maybe we could try to properly fix it? I’ve no idea, will think about it

**Comment by mattst** [comment]
v. 0.5.4 is working fine on ST v. 2.0.2 Build 2221.

Thanks very much.

**Comment by vovkkk** [comment]
@mattst could you please test [branch](https://github.com/aziz/SublimeFileBrowser/tree/x-issue62)—it is supposed to refresh existing FileBrowser tabs on restarting ST2, seems to work but I’m not sure.

/cc @aziz

**Comment by aziz** [comment]
:+1:

**Comment by vovkkk** [comment]
@aziz does it work for you? I made more testing and sometimes it fails, seems depend on startup time or something.

Guess, I’ll increase time out to 1000 ms and exit if active_window is none so it will cause no refresh sometimes, unless you have better idea.
The worst is api have to be called on main thread, but while loop would block everything, so if we call on main thread then ST will never start, if we call on separate thread then set_timeout always return none and we will never know if active_window return actual reference… boo.

**Comment by vovkkk** [comment]
Trying recursion (in the same branch). Let me know what you think and if it works for you

With recursion and 100 ms timeout on each call we have about 1 minute and 40 seconds to refresh — pretty enough I think. on my machine it takes ≈ 3 recursive calls on startup.

**Comment by mattst** [comment]
@vovkkk

Using: SublimeFileBrowser Branch x-issue62 on ST v.2.0.2 Build 2221 (Linux 64)

The bug I reported is now resolved, the plugin loads without reporting errors.

Tests:

I closed and re-started ST 5 times and the plugin loaded on all occasions without errors.

I opened 3 SublimeFileBrowser tabs on different test directories and was able to rename files in all and swap backwards and forwards between them all renaming files as I went without any problems.

**As requested:** With the ST option "remember_open_files" set to true I closed ST with between 1 and 3 SublimeFileBrowser tabs displaying different directories, as well as some tabs with text files open. When re-starting ST none of the SublimeFileBrowser tabs were ever restored, although all the text files' tabs were successfully restored.

##### IMPORTANT NEW BUG

While opening a directory from the input panel I used tab to autocomplete a directory name, this worked fine when completing a unique name - e.g. type 'z' with only one directory beginning with 'z' and it autocompletes - however when the autocomplete feature had several directory name completion possibilities the overlay panel was NOT displayed showing the list, instead a new tab was opened showing all of the directory name completion possibilities each on a new line. This new tab was called '\*completions\*', it had the same background colour as a SublimeFileBrowser tab, and as soon as ESC was pressed to close the input panel the '\*completions\*' tab automatically closed along with the input panel.

Since this autocomplete bug is of significance I checked to see if it had been introduced into the SublimeFileBrowser version for ST v.3. Unfortunately the same thing happens with SublimeFileBrowser v.0.5.4 on ST v.3 Build 3065.

Please also note that the help/shortcuts facility is also broken. A new tab called 'Browse: shortcuts' opens when '?' is pressed, the tab has the same background colour as SublimeFileBrowser, but NO text at all is displayed in the tab. This happens in both 'Branch x-issue62' on ST v.2.0.2 Build 2221 and in SublimeFileBrowser v.0.5.4 on ST v.3 Build 3065.

Sorry to be the bearer of bad news. I hope this helps.

**Comment by mattst** [comment]
@vovkkk

> Also just in case: I added another commit in the same branch
> 39 minute ago, please make sure you get it, not old one.

Okay, I mucked up, oops. I thought that if I clicked on a branch on the github page to switch to that branch then the "HTTPS clone URL" (on right of page) would be correct for that branch. Nope, that just clones the master. So the commit I was testing was:

    Specific commit: b20da129d819b216... clean up code

I worked out that to clone the branch I needed to do this:

    git clone -b x-issue62 https://github.com/aziz/SublimeFileBrowser.git

Now Using: SublimeFileBrowser Branch x-issue62 on ST v.2.0.2 Build 2221 (Linux 64)

    Specific commit: 9ac6fa2aeebfe804... Fix #62 (recursive plugin_loaded for ST2)


> Like closed? or what you mean exactly?

Yes, quitting the application. You wrote:

> @mattst could you please test branch—it is supposed to refresh existing
> FileBrowser tabs on restarting ST2, seems to work but I’m not sure.

You asked me to see if existing FileBrowser tabs were refreshed on restarting ST2. With commit 9ac6fa2aee they are not, no FileBrowser tabs are restored at all when ST2 is restarted. To be absolutely clear - the FileBrowser tabs are not restored so there is nothing to refresh, all text tabs are correctly restored. [Note: In v.0.5.4 on ST v.3 Build 3065 FileBrowser tabs are both restored and refreshed.]

> This is feature, as far as I concern, iirc it was implemented in original
> dired (right?), but we had plan to change it. Either that or I’m completely
> missing your point.

With regards to autocomplete... I think I got muddled with the behaviour of another plugin. [I don't know about dired as I've never installed it.]

The [iOpener](https://github.com/rosshemsley/iOpener) plugin allows opening files from the input panel in a similar way to how FileBrowser allows the selection of a directory. Tab completion in both is performed inplace in the input panel. In iOpener if there are multiple completion possibilities when tab is pressed then the overlay panel (at the top) is displayed showing the completion possibilities, the user can then select which one they want and it is inserted into the path shown in the input panel. If you aren't sure what I mean, have a look at the gif animation on the [iOpener github page](https://github.com/rosshemsley/iOpener).

I guess from what you wrote that this is not what FileBrowser does and that a tab showing the completion possibilities is displayed instead of selection from the overlay panel. In which case it's working fine. Sorry for any confusion created about this.

The help/shortcuts tab now works fine in ST2 with FileBrowser commit 9ac6fa2aee. It is not working in FileBrowser v.0.5.4 on ST v.3 Build 3065 but I think you know that already.

I hope this calrifies everything.

**Comment by vovkkk** [comment]
I’ve tested on Linux it works somewhat, sometimes it fails, especially if I add new file into directory, I can’t comprehend it, but sometimes it works so it’s better than nothing.



> To be absolutely clear - the FileBrowser tabs are not restored so there is nothing to refresh

this is really weird, I don’t observe such anomaly neither on Windows nor on Linux, could you please try ST2 32bit? or let me know which other plugins you have.

> If you aren't sure what I mean…

Yea, it is [planned](https://github.com/aziz/SublimeFileBrowser/issues/61#issuecomment-71625103)

**Comment by vovkkk** [comment]
Fails were because view must be loaded before refresh, so now it’s fixed in same branch, if no feedback I’ll release it tomorrow.
