### ISSUE TITLE
Errors when opening file browser (MacOS 10.11 related?)

### ISSUE THREAD

**Issue by Reinmar** [aziz/SublimeFileBrowser#97]
I'm not sure whether this started after upgrading MacOS to 10.11 or because my installation of SublimeFileBrowser was automatically upgraded at that same time (it might have been the first time I closed ST3 in a month :D), but:

* on 0.7.7 everything works fine.
* starting from 0.7.8 (and including 0.7.9) I have an error when opening the file browser:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 177, in run
    self.re_populate_view(edit, path, names, expanded, to_expand, toggle)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 205, in re_populate_view
    tree = self.traverse_tree(root, root, '', names, expanded)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 254, in traverse_tree
    tree[~0] += u'\t<%s>' % error
IndexError: list index out of range
```

I'm running ST3 build 3083.

**Comment by vovkkk** [comment]
Could you describe in detail how exactly you open it? And I mean in detail.
Did you try reinstall plugin? closing all tabs and restart ST?
Do you have read permission for directory you try to browse?

Everything works fine for me on Win8.

**Comment by Reinmar** [comment]
I've got this keystroke defined:

```
	{
		"keys": ["command+o"],
		"command": "dired",
		"args": {
			"immediate": true,
			"single_pane": true
		}
	},
```

I close ST3, check out FileBrowser to 0.7.9, open ST3 (important: I have one file opened already) and press <kbd>Cmd+O</kbd>. A new tab appears, but it's empty. In the console I can see the error log I posted earlier.

It works fine when I press <kbd>Cmd+O</kbd> when I don't have any file opened. Then file browser opens correctly. However, it fails to open when I press <kbd>Cmd+O</kbd> again.

I didn't try to reinstall the plugin but I moved `FileBrowser` dir to another place, restarted ST3, moved it back and restarted again. I guess it counts as reinstalling :D.

There should be no problems with permissions as sometimes everything works fine (when there are no files opened).

**Comment by vovkkk** [comment]
Could you replace [these lines](https://github.com/aziz/SublimeFileBrowser/blob/master/dired.py#L253-L255) in your local copy with following

```python
            if error:
                print(error)
                tree[~0] += u'\t<%s>' % error
                return
```

and tell me what it prints in console before the traceback.

**Comment by Reinmar** [comment]
```
[Errno 2] No such file or directory: '/www/ckeditor-/'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 177, in run
    self.re_populate_view(edit, path, names, expanded, to_expand, toggle)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 205, in re_populate_view
    tree = self.traverse_tree(root, root, '', names, expanded)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 255, in traverse_tree
    tree[~0] += u'\t<%s>' % error
IndexError: list index out of range
```

So, indeed there's no `ckeditor-` directory. Instead, I've got `/www/ckeditor-dev/`. The currently loaded file is directly inside this directory, so when I press <kbd>Cmd+O</kbd> the file browser is most likely trying to list files in `/www/ckeditor-dev/`.

This is the real list of files in this directory:

```
(master c566732) p@m /www/ckeditor-dev> ls -la
total 576
drwxr-xr-x   30 p  staff    1020  1 Oct 13:06 .
drwxr-xr-x   27 p  staff     918 28 Sep 11:35 ..
-rw-r--r--@   1 p  staff   16388 10 Sep 13:14 .DS_Store
drwxr-xr-x   12 p  staff     408  2 Oct 18:46 .bender
-rw-r--r--    1 p  staff     219 31 Aug 15:14 .editorconfig
drwxr-xr-x   19 p  staff     646  5 Oct 22:12 .git
-rw-r--r--    1 p  staff     197 31 Aug 15:14 .gitattributes
-rw-r--r--    1 p  staff     508  2 Sep 12:25 .gitignore
-rw-r--r--    1 p  staff    1653 30 Sep 16:13 .jscsrc
-rw-r--r--    1 p  staff     449 30 Sep 16:13 .jshintrc
-rw-r--r--    1 p  staff    1979  1 Jul 17:10 .mailmap
-rw-r--r--    1 p  staff  124764  1 Oct 13:06 CHANGES.md
-rw-r--r--    1 p  staff   86700 29 Sep 13:40 LICENSE.md
-rw-r--r--    1 p  staff    3161 29 Sep 13:40 README.md
drwxr-xr-x    3 p  staff     102 31 Aug 15:14 adapters
-rw-r--r--    1 p  staff    1561 30 Sep 16:13 bender.js
-rw-r--r--    1 p  staff    3220 31 Aug 15:14 ckeditor.js
-rw-r--r--    1 p  staff    1345  2 Sep 12:44 config.js
-rw-r--r--    1 p  staff    1835  7 Sep 15:01 contents.css
drwxr-xr-x   40 p  staff    1360 30 Sep 16:13 core
drwxr-xr-x   10 p  staff     340 31 Aug 15:14 dev
-rw-r--r--    1 p  staff    1771 31 Aug 15:14 gruntfile.js
drwxr-xr-x   69 p  staff    2346 29 Sep 13:40 lang
drwxr-xr-x   20 p  staff     680  1 Oct 13:01 node_modules
-rw-r--r--    1 p  staff    1029  1 Oct 13:00 package.json
drwxr-xr-x  104 p  staff    3536 31 Aug 15:14 plugins
drwxr-xr-x   11 p  staff     374  7 Sep 13:42 samples
drwxr-xr-x    5 p  staff     170  1 Dec  2014 skins
-rw-r--r--    1 p  staff    3529 31 Aug 15:14 styles.js
drwxr-xr-x   11 p  staff     374 31 Aug 15:13 tests
```

**Comment by Reinmar** [comment]
I also made a test that if the currently opened file is deeper in the tree structure, the same error occurs. That reminded me that recently I noticed that the file browser stopped opening the current directory, but every time fallbacks to the main project's directory. This happened for some time and then started working again (I think).

**Comment by Reinmar** [comment]
And one more thing (see the first line):

![screen shot 2015-10-05 at 22 21 37](https://cloud.githubusercontent.com/assets/156149/10292423/7a60ca9e-6baf-11e5-9adb-0c2ac4464f39.png)

Unfortunately, I'm not quite sure how to reproduce it :D.

**Comment by Reinmar** [comment]
I don't know Python, but I tried to track the problem and found that if after this line https://github.com/aziz/SublimeFileBrowser/blob/master/dired.py#L103 I add:

```
                print(root, path, folders)
```

I get:

```
/www/ckeditor- /www/ckeditor-dev/CHANGES.md ['/www/ckeditor-dev', '/www/ckeditor-sdk', '/www/ckeditor-docs']
```

So there's something weird with `os.path.commonprefix` :D.

**Comment by Reinmar** [comment]
OK, the docs say:

> os.path.commonprefix(list)
> Return the longest path prefix (taken character-by-character) that is a prefix of all paths in list. If list is empty, return the empty string (''). Note that this may return **invalid paths** because it works a character at a time.

So this makes sense.

**Comment by vovkkk** [comment]
Nice, that helped.

Could you replace this method with following:

```python
    def _determine_path(self):
        '''Return (path, fname) so goto=fname to set cursor'''
        # Use the current view's directory if it has one.
        view = self.window.active_view()
        path = view and view.file_name()
        folders = self.window.folders()
        if path:
            if not folders:
                return os.path.split(path)
            for f in folders:
                if path.startswith(f):
                    root = os.path.commonprefix([path, f])
                    return (root, path)
```

Does it fix the problem?

**Comment by vovkkk** [comment]
Um, on second thought, the code should be:

```python 
    def _determine_path(self):
        '''Return (path, fname) so goto=fname to set cursor'''
        # Use the current view's directory if it has one.
        view = self.window.active_view()
        path = view and view.file_name()
        folders = self.window.folders()
        if path:
            if not folders:
                return os.path.split(path)
            for f in folders:
                if path.startswith(f):
                    return (f, path)
```

**Comment by Reinmar** [comment]
I've got this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "/Users/p/Library/Application Support/Sublime Text 3/Packages/FileBrowser/dired.py", line 65, in run
    path, goto = self._determine_path()
TypeError: 'NoneType' object is not iterable
```

But at least for me the error does not make sense ;|.

Just to clarify – `folders` contains:

```
['/www/ckeditor-dev', '/www/ckeditor-sdk', '/www/ckeditor-docs']
```

**Comment by vovkkk** [comment]
The error means that method returns None.
Perhaps I was not precise enough, the method should be:

```python
    def _determine_path(self):
        '''Return (path, fname) so goto=fname to set cursor'''
        # Use the current view's directory if it has one.
        view = self.window.active_view()
        path = view and view.file_name()
        folders = self.window.folders()
        if path:
            for f in folders:
                if path.startswith(f):
                    return (f, path)
            return os.path.split(path)

        # Use the first project folder if there is one.
        data = self.window.project_data() if ST3 else None
        if data and 'folders' in data:
            folders = data['folders']
            if folders:
                return (folders[0]['path'], '')

        # Use window folder if possible
        if len(folders) > 0:
            return (folders[0], '')

        # Use the user's home directory.
        return (os.path.expanduser('~'), '')
```

**Comment by vovkkk** [comment]
I’ve released a new version, pretty sure it fixes the issue.
Let me know if something is wrong.

**Comment by Reinmar** [comment]
It seems to work fine. Thanks! :)
